version: '3'

services:

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
  db:
    image: postgres:16
    container_name: db

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata


  app:
    container_name: spa_web_application
    build: .
    tty: true
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8001:8000'
    depends_on:
      - db
  celery:
    build: .
    tty: true
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    tty: true
    command: celery -A config beat --loglevel=info
    depends_on:
      - redis
      - app





volumes:
  pg_data:

