# Generated by Django 4.2.4 on 2023-09-29 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):  # pragma: no cover

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место выполнения привычки')),
                ('time', models.TimeField(null=True, verbose_name='время выполнения привычки')),
                ('action', models.CharField(max_length=100, verbose_name='действие привычки')),
                ('pleasant', models.BooleanField(default=False, null=True, verbose_name='признак приятной привычки')),
                ('frequency', models.PositiveIntegerField(default=1, verbose_name='периодичность привычки')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='вознаграждение')),
                ('time_required', models.IntegerField(null=True, verbose_name='время на выполнение привычки')),
                ('public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['id'],
            },
        ),
    ]
